[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# This redirect rule ensures all routes are handled by Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

