[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Enable build cache for faster builds
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# This redirect rule ensures all routes are handled by Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers to ensure CSS and other assets are properly loaded
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

